repos:
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.13.2
      hooks:
      - id: ruff
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
    - repo: local
      hooks:
      - id: ruff check
        name: Run Ruff via uv
        entry: uv run ruff check
        language: system
        types: [python]
      - id: ruff check
        name: Format with Ruff via uv
        entry: uv run ruff check --fix
        language: system
        types: [ python ]
      - id: pytest changed files
        name: Run pytest on changed files
        entry: uv run pytest ./tests
        language: script
        types: [ python ]
